/*
 SMAddress.m
 SMARTFramework
 
 Generated by build-obj-c-classes.py on 2013-06-14.
 Copyright (c) 2013 CHIP, Boston Children's Hospital
 
 This library is free software; you can redistribute it and/or
 modify it under the terms of the GNU Lesser General Public
 License as published by the Free Software Foundation; either
 version 2.1 of the License, or (at your option) any later version.
 
 This library is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 Lesser General Public License for more details.
 
 You should have received a copy of the GNU Lesser General Public
 License along with this library; if not, write to the Free Software
 Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA
 */

#import "SMAddress.h"
#import "SMARTObjects.h"

#import <Redland-ObjC.h>


@implementation SMAddress


#pragma mark - Synthesized Lazy Getter
@synthesize countryName = _countryName;

- (NSString *)countryName
{
	if (!_countryName) {
		RedlandNode *predicate = [RedlandNode nodeWithURIString:@"http://www.w3.org/2006/vcard/ns#country-name"];
		RedlandStatement *statement = [RedlandStatement statementWithSubject:self.subject predicate:predicate object:nil];
		RedlandStreamEnumerator *query = [self.inModel enumeratorOfStatementsLike:statement];
		
		RedlandStatement *rslt = [query nextObject];
		_countryName = [rslt.object literalValue];
	}
	return _countryName;
}

- (void)setCountryName:(NSString *)countryName
{
	if (countryName != _countryName) {
		RedlandNode *predicate = (countryName || _countryName) ? [RedlandNode nodeWithURIString:@"http://www.w3.org/2006/vcard/ns#country-name"] : nil;
		if (_countryName) {
			[self.inModel removeStatementsLike:[RedlandStatement statementWithSubject:self.subject predicate:predicate object:nil]];
		}
		
		_countryName = [countryName copy];
		
		if (_countryName) {
			[self.inModel addStatement:[RedlandStatement statementWithSubject:self.subject predicate:predicate object:[_countryName nodeValue]]];
		}
	}
}

@synthesize extendedAddress = _extendedAddress;

- (NSString *)extendedAddress
{
	if (!_extendedAddress) {
		RedlandNode *predicate = [RedlandNode nodeWithURIString:@"http://www.w3.org/2006/vcard/ns#extended-address"];
		RedlandStatement *statement = [RedlandStatement statementWithSubject:self.subject predicate:predicate object:nil];
		RedlandStreamEnumerator *query = [self.inModel enumeratorOfStatementsLike:statement];
		
		RedlandStatement *rslt = [query nextObject];
		_extendedAddress = [rslt.object literalValue];
	}
	return _extendedAddress;
}

- (void)setExtendedAddress:(NSString *)extendedAddress
{
	if (extendedAddress != _extendedAddress) {
		RedlandNode *predicate = (extendedAddress || _extendedAddress) ? [RedlandNode nodeWithURIString:@"http://www.w3.org/2006/vcard/ns#extended-address"] : nil;
		if (_extendedAddress) {
			[self.inModel removeStatementsLike:[RedlandStatement statementWithSubject:self.subject predicate:predicate object:nil]];
		}
		
		_extendedAddress = [extendedAddress copy];
		
		if (_extendedAddress) {
			[self.inModel addStatement:[RedlandStatement statementWithSubject:self.subject predicate:predicate object:[_extendedAddress nodeValue]]];
		}
	}
}

@synthesize locality = _locality;

- (NSString *)locality
{
	if (!_locality) {
		RedlandNode *predicate = [RedlandNode nodeWithURIString:@"http://www.w3.org/2006/vcard/ns#locality"];
		RedlandStatement *statement = [RedlandStatement statementWithSubject:self.subject predicate:predicate object:nil];
		RedlandStreamEnumerator *query = [self.inModel enumeratorOfStatementsLike:statement];
		
		RedlandStatement *rslt = [query nextObject];
		_locality = [rslt.object literalValue];
	}
	return _locality;
}

- (void)setLocality:(NSString *)locality
{
	if (locality != _locality) {
		RedlandNode *predicate = (locality || _locality) ? [RedlandNode nodeWithURIString:@"http://www.w3.org/2006/vcard/ns#locality"] : nil;
		if (_locality) {
			[self.inModel removeStatementsLike:[RedlandStatement statementWithSubject:self.subject predicate:predicate object:nil]];
		}
		
		_locality = [locality copy];
		
		if (_locality) {
			[self.inModel addStatement:[RedlandStatement statementWithSubject:self.subject predicate:predicate object:[_locality nodeValue]]];
		}
	}
}

@synthesize postalCode = _postalCode;

- (NSString *)postalCode
{
	if (!_postalCode) {
		RedlandNode *predicate = [RedlandNode nodeWithURIString:@"http://www.w3.org/2006/vcard/ns#postal-code"];
		RedlandStatement *statement = [RedlandStatement statementWithSubject:self.subject predicate:predicate object:nil];
		RedlandStreamEnumerator *query = [self.inModel enumeratorOfStatementsLike:statement];
		
		RedlandStatement *rslt = [query nextObject];
		_postalCode = [rslt.object literalValue];
	}
	return _postalCode;
}

- (void)setPostalCode:(NSString *)postalCode
{
	if (postalCode != _postalCode) {
		RedlandNode *predicate = (postalCode || _postalCode) ? [RedlandNode nodeWithURIString:@"http://www.w3.org/2006/vcard/ns#postal-code"] : nil;
		if (_postalCode) {
			[self.inModel removeStatementsLike:[RedlandStatement statementWithSubject:self.subject predicate:predicate object:nil]];
		}
		
		_postalCode = [postalCode copy];
		
		if (_postalCode) {
			[self.inModel addStatement:[RedlandStatement statementWithSubject:self.subject predicate:predicate object:[_postalCode nodeValue]]];
		}
	}
}

@synthesize region = _region;

- (NSString *)region
{
	if (!_region) {
		RedlandNode *predicate = [RedlandNode nodeWithURIString:@"http://www.w3.org/2006/vcard/ns#region"];
		RedlandStatement *statement = [RedlandStatement statementWithSubject:self.subject predicate:predicate object:nil];
		RedlandStreamEnumerator *query = [self.inModel enumeratorOfStatementsLike:statement];
		
		RedlandStatement *rslt = [query nextObject];
		_region = [rslt.object literalValue];
	}
	return _region;
}

- (void)setRegion:(NSString *)region
{
	if (region != _region) {
		RedlandNode *predicate = (region || _region) ? [RedlandNode nodeWithURIString:@"http://www.w3.org/2006/vcard/ns#region"] : nil;
		if (_region) {
			[self.inModel removeStatementsLike:[RedlandStatement statementWithSubject:self.subject predicate:predicate object:nil]];
		}
		
		_region = [region copy];
		
		if (_region) {
			[self.inModel addStatement:[RedlandStatement statementWithSubject:self.subject predicate:predicate object:[_region nodeValue]]];
		}
	}
}

@synthesize streetAddress = _streetAddress;

- (NSString *)streetAddress
{
	if (!_streetAddress) {
		RedlandNode *predicate = [RedlandNode nodeWithURIString:@"http://www.w3.org/2006/vcard/ns#street-address"];
		RedlandStatement *statement = [RedlandStatement statementWithSubject:self.subject predicate:predicate object:nil];
		RedlandStreamEnumerator *query = [self.inModel enumeratorOfStatementsLike:statement];
		
		RedlandStatement *rslt = [query nextObject];
		_streetAddress = [rslt.object literalValue];
	}
	return _streetAddress;
}

- (void)setStreetAddress:(NSString *)streetAddress
{
	if (streetAddress != _streetAddress) {
		RedlandNode *predicate = (streetAddress || _streetAddress) ? [RedlandNode nodeWithURIString:@"http://www.w3.org/2006/vcard/ns#street-address"] : nil;
		if (_streetAddress) {
			[self.inModel removeStatementsLike:[RedlandStatement statementWithSubject:self.subject predicate:predicate object:nil]];
		}
		
		_streetAddress = [streetAddress copy];
		
		if (_streetAddress) {
			[self.inModel addStatement:[RedlandStatement statementWithSubject:self.subject predicate:predicate object:[_streetAddress nodeValue]]];
		}
	}
}



#pragma mark - Class Properties
+ (NSString *)rdfType
{
	return @"http://www.w3.org/2006/vcard/ns#Address";
}




@end
