/*
 SMAllergy.h
 SMARTFramework
 
 Generated by build-obj-c-classes.py on 2013-06-13.
 Copyright (c) 2013 CHIP, Boston Children's Hospital
 
 This library is free software; you can redistribute it and/or
 modify it under the terms of the GNU Lesser General Public
 License as published by the Free Software Foundation; either
 version 2.1 of the License, or (at your option) any later version.
 
 This library is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 Lesser General Public License for more details.
 
 You should have received a copy of the GNU Lesser General Public
 License along with this library; if not, write to the Free Software
 Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA
 */

#import "SMBaseDocument.h"

@class SMCodedValue, SMMedicalRecord;


/**
 *  A class representing "http://smartplatforms.org/terms#Allergy" objects, generated from the SMART ontology.
 */
@interface SMAllergy : SMBaseDocument

/// Representing http://smartplatforms.org/terms#allergicReaction as SMCodedValue
@property (nonatomic, strong) SMCodedValue *allergicReaction;

/// Representing http://smartplatforms.org/terms#belongsTo as SMMedicalRecord
@property (nonatomic, strong) SMMedicalRecord *belongsTo;

/// Representing http://smartplatforms.org/terms#category as SMCodedValue
@property (nonatomic, strong) SMCodedValue *category;

/// Representing http://smartplatforms.org/terms#drugAllergen as SMCodedValue
@property (nonatomic, strong) SMCodedValue *drugAllergen;

/// Representing http://smartplatforms.org/terms#drugClassAllergen as SMCodedValue
@property (nonatomic, strong) SMCodedValue *drugClassAllergen;

/// Representing http://smartplatforms.org/terms#endDate as NSString
@property (nonatomic, copy) NSString *endDate;

/// Representing http://smartplatforms.org/terms#otherAllergen as SMCodedValue
@property (nonatomic, strong) SMCodedValue *otherAllergen;

/// Representing http://smartplatforms.org/terms#severity as SMCodedValue
@property (nonatomic, strong) SMCodedValue *severity;

/// Representing http://smartplatforms.org/terms#startDate as NSString
@property (nonatomic, copy) NSString *startDate;


@end
