/*
 SMCodeProvenance.m
 SMARTFramework
 
 Generated by build-obj-c-classes.py on 2013-06-14.
 Copyright (c) 2013 CHIP, Boston Children's Hospital
 
 This library is free software; you can redistribute it and/or
 modify it under the terms of the GNU Lesser General Public
 License as published by the Free Software Foundation; either
 version 2.1 of the License, or (at your option) any later version.
 
 This library is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 Lesser General Public License for more details.
 
 You should have received a copy of the GNU Lesser General Public
 License along with this library; if not, write to the Free Software
 Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA
 */

#import "SMCodeProvenance.h"
#import "SMARTObjects.h"

#import <Redland-ObjC.h>


@implementation SMCodeProvenance


#pragma mark - Synthesized Lazy Getter
@synthesize sourceCode = _sourceCode;

- (NSString *)sourceCode
{
	if (!_sourceCode) {
		RedlandNode *predicate = [RedlandNode nodeWithURIString:@"http://smartplatforms.org/terms#sourceCode"];
		RedlandStatement *statement = [RedlandStatement statementWithSubject:self.subject predicate:predicate object:nil];
		RedlandStreamEnumerator *query = [self.inModel enumeratorOfStatementsLike:statement];
		
		RedlandStatement *rslt = [query nextObject];
		_sourceCode = [rslt.object literalValue];
	}
	return _sourceCode;
}

- (void)setSourceCode:(NSString *)sourceCode
{
	if (sourceCode != _sourceCode) {
		RedlandNode *predicate = (sourceCode || _sourceCode) ? [RedlandNode nodeWithURIString:@"http://smartplatforms.org/terms#sourceCode"] : nil;
		if (_sourceCode) {
			[self.inModel removeStatementsLike:[RedlandStatement statementWithSubject:self.subject predicate:predicate object:nil]];
		}
		
		_sourceCode = [sourceCode copy];
		
		if (_sourceCode) {
			[self.inModel addStatement:[RedlandStatement statementWithSubject:self.subject predicate:predicate object:[_sourceCode nodeValue]]];
		}
	}
}

@synthesize title = _title;

- (NSString *)title
{
	if (!_title) {
		RedlandNode *predicate = [RedlandNode nodeWithURIString:@"http://purl.org/dc/terms/title"];
		RedlandStatement *statement = [RedlandStatement statementWithSubject:self.subject predicate:predicate object:nil];
		RedlandStreamEnumerator *query = [self.inModel enumeratorOfStatementsLike:statement];
		
		RedlandStatement *rslt = [query nextObject];
		_title = [rslt.object literalValue];
	}
	return _title;
}

- (void)setTitle:(NSString *)title
{
	if (title != _title) {
		RedlandNode *predicate = (title || _title) ? [RedlandNode nodeWithURIString:@"http://purl.org/dc/terms/title"] : nil;
		if (_title) {
			[self.inModel removeStatementsLike:[RedlandStatement statementWithSubject:self.subject predicate:predicate object:nil]];
		}
		
		_title = [title copy];
		
		if (_title) {
			[self.inModel addStatement:[RedlandStatement statementWithSubject:self.subject predicate:predicate object:[_title nodeValue]]];
		}
	}
}

@synthesize translationFidelity = _translationFidelity;

- (SMCodedValue *)translationFidelity
{
	if (!_translationFidelity) {
		
		// get the "translationFidelity" element
		RedlandNode *predicate = [RedlandNode nodeWithURIString:@"http://smartplatforms.org/terms#translationFidelity"];
		RedlandStatement *statement = [RedlandStatement statementWithSubject:self.subject predicate:predicate object:nil];
		RedlandStreamEnumerator *query = [self.inModel enumeratorOfStatementsLike:statement];
		RedlandStatement *rslt = [query nextObject];
		
		// create an item for this object
		SMCodedValue *obj = [SMCodedValue newWithSubject:rslt.object inModel:self.inModel];
		_translationFidelity = obj ? obj : (id)[NSNull null];
	}
	
	// we use NSNull as a placeholder in case we already searched the graph and haven't found the object. This should help with performance.
	if ((id)[NSNull null] == _translationFidelity) {
		return nil;
	}
	
	return _translationFidelity;
}

- (void)setTranslationFidelity:(SMCodedValue *)translationFidelity
{
	if (translationFidelity != _translationFidelity) {
		RedlandNode *predicate = (translationFidelity || _translationFidelity) ? [RedlandNode nodeWithURIString:@"http://smartplatforms.org/terms#translationFidelity"] : nil;
		if (_translationFidelity) {
			[self.inModel removeSubmodel:_translationFidelity.model];
			[self.inModel removeStatementsLike:[RedlandStatement statementWithSubject:self.subject predicate:predicate object:nil]];
		}
		
		_translationFidelity = translationFidelity;
		
		if (_translationFidelity) {
			[self.inModel addStatement:[RedlandStatement statementWithSubject:self.subject predicate:predicate object:_translationFidelity.subject]];
			[self.inModel addSubmodel:_translationFidelity.model];
		}
	}
}



#pragma mark - Class Properties
+ (NSString *)rdfType
{
	return @"http://smartplatforms.org/terms#CodeProvenance";
}




@end
