/*
 SMFulfillment.h
 SMARTFramework
 
 Generated by build-obj-c-classes.py on 2013-06-14.
 Copyright (c) 2013 CHIP, Boston Children's Hospital
 
 This library is free software; you can redistribute it and/or
 modify it under the terms of the GNU Lesser General Public
 License as published by the Free Software Foundation; either
 version 2.1 of the License, or (at your option) any later version.
 
 This library is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 Lesser General Public License for more details.
 
 You should have received a copy of the GNU Lesser General Public
 License along with this library; if not, write to the Free Software
 Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA
 */

#import "SMBaseDocument.h"

@class SMMedicalRecord, SMMedication, SMPharmacy, SMProvider, SMValueAndUnit;


/**
 *  A class representing "http://smartplatforms.org/terms#Fulfillment" objects, generated from the SMART ontology.
 */
@interface SMFulfillment : SMBaseDocument

/// Representing http://smartplatforms.org/terms#belongsTo as SMMedicalRecord
@property (nonatomic, strong) SMMedicalRecord *belongsTo;

/// Representing http://purl.org/dc/terms/date as NSString
@property (nonatomic, copy) NSString *date;

/// Representing http://smartplatforms.org/terms#dispenseDaysSupply as NSString
@property (nonatomic, copy) NSString *dispenseDaysSupply;

/// Representing http://smartplatforms.org/terms#medication as SMMedication
@property (nonatomic, strong) SMMedication *medication;

/// Representing http://smartplatforms.org/terms#pbm as NSString
@property (nonatomic, copy) NSString *pbm;

/// Representing http://smartplatforms.org/terms#pharmacy as SMPharmacy
@property (nonatomic, strong) SMPharmacy *pharmacy;

/// Representing http://smartplatforms.org/terms#provider as SMProvider
@property (nonatomic, strong) SMProvider *provider;

/// Representing http://smartplatforms.org/terms#quantityDispensed as SMValueAndUnit
@property (nonatomic, strong) SMValueAndUnit *quantityDispensed;


@end
