/*
 SMRecord+Calls.h
 SMARTFramework
 
 Generated by build-obj-c-classes.py on 2013-04-01.
 Copyright (c) 2013 CHIP, Boston Children's Hospital
 
 This library is free software; you can redistribute it and/or
 modify it under the terms of the GNU Lesser General Public
 License as published by the Free Software Foundation; either
 version 2.1 of the License, or (at your option) any later version.
 
 This library is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 Lesser General Public License for more details.
 
 You should have received a copy of the GNU Lesser General Public
 License along with this library; if not, write to the Free Software
 Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA
 */

#import "SMRecord.h"
#import "SMART.h"


/**
 *  A category on SMRecord, generated from the SMART ontology.
 */
@interface SMRecord(Calls)

- (void)getAllergies:(SMSuccessRetvalueBlock)callback;
- (void)getClinicalNotes:(SMSuccessRetvalueBlock)callback;
- (void)getDemographics:(SMSuccessRetvalueBlock)callback;
- (void)getDocuments:(SMSuccessRetvalueBlock)callback;
- (void)getEncounters:(SMSuccessRetvalueBlock)callback;
- (void)getFamilyHistoryObservations:(SMSuccessRetvalueBlock)callback;
- (void)getFulfillments:(SMSuccessRetvalueBlock)callback;
- (void)getImmunizations:(SMSuccessRetvalueBlock)callback;
- (void)getLabPanel:(SMSuccessRetvalueBlock)callback;
- (void)getLabPanels:(SMSuccessRetvalueBlock)callback;
- (void)getLabResults:(SMSuccessRetvalueBlock)callback;
- (void)getMedications:(SMSuccessRetvalueBlock)callback;
- (void)getPhotograph:(SMSuccessRetvalueBlock)callback;
- (void)getProblems:(SMSuccessRetvalueBlock)callback;
- (void)getProcedures:(SMSuccessRetvalueBlock)callback;
- (void)getSocialHistory:(SMSuccessRetvalueBlock)callback;
- (void)getVitalSignSets:(SMSuccessRetvalueBlock)callback;
- (void)postClinicalNote:(SMSuccessRetvalueBlock)callback;


@end
