/*
 SMFamilyHistory.h
 SMARTFramework
 
 Generated by build-obj-c-classes.py on 2013-02-20.
 Copyright (c) 2013 CHIP, Boston Children's Hospital
 
 This library is free software; you can redistribute it and/or
 modify it under the terms of the GNU Lesser General Public
 License as published by the Free Software Foundation; either
 version 2.1 of the License, or (at your option) any later version.
 
 This library is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 Lesser General Public License for more details.
 
 You should have received a copy of the GNU Lesser General Public
 License along with this library; if not, write to the Free Software
 Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA
 */

#import "SMBaseDocument.h"

@class SMCodedValue, SMMedicalRecord, SMVitalSign;


/**
 *  A class representing "http://smartplatforms.org/terms#FamilyHistory" objects, generated from the SMART ontology.
 */
@interface SMFamilyHistory : SMBaseDocument

/// Representing http://smartplatforms.org/terms#aboutRelative
@property (nonatomic, strong) SMCodedValue *aboutRelative;

/// Representing http://www.w3.org/2006/vcard/ns#bday
@property (nonatomic, copy) NSString *bday;

/// Representing http://smartplatforms.org/terms#belongsTo
@property (nonatomic, strong) SMMedicalRecord *belongsTo;

/// Representing http://www.w3.org/2006/vcard/ns#deathdate
@property (nonatomic, copy) NSString *deathdate;

/// Representing http://smartplatforms.org/terms#hasProblem
@property (nonatomic, copy) NSArray *hasProblem;

/// Representing http://smartplatforms.org/terms#height
@property (nonatomic, strong) SMVitalSign *height;


@end
