/*
 SMMedication.h
 SMARTFramework
 
 Generated by build-obj-c-classes.py on 2012-10-01.
 Copyright (c) 2012 CHIP, Boston Children's Hospital
 
 This library is free software; you can redistribute it and/or
 modify it under the terms of the GNU Lesser General Public
 License as published by the Free Software Foundation; either
 version 2.1 of the License, or (at your option) any later version.
 
 This library is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 Lesser General Public License for more details.
 
 You should have received a copy of the GNU Lesser General Public
 License along with this library; if not, write to the Free Software
 Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA
 */

#import "SMDocument.h"

@class SMCode, SMCodedValue, SMFulfillment, SMMedicalRecord, SMValueAndUnit;


/**
 *  A class representing "http://smartplatforms.org/terms#Medication" objects, generated from smart.owl.
 */
@interface SMMedication : SMDocument

/// Representing http://smartplatforms.org/terms#belongsTo
@property (nonatomic, strong) SMMedicalRecord *belongsTo;

/// Representing http://smartplatforms.org/terms#drugName
@property (nonatomic, strong) SMCodedValue *drugName;

/// Representing http://smartplatforms.org/terms#endDate
@property (nonatomic, copy) NSString *endDate;

/// Representing http://smartplatforms.org/terms#frequency
@property (nonatomic, strong) SMValueAndUnit *frequency;

/// Representing http://smartplatforms.org/terms#fulfillment
@property (nonatomic, copy) NSArray *fulfillment;

/// Representing http://smartplatforms.org/terms#instructions
@property (nonatomic, copy) NSString *instructions;

/// Representing http://smartplatforms.org/terms#provenance
@property (nonatomic, copy) NSArray *provenance;

/// Representing http://smartplatforms.org/terms#quantity
@property (nonatomic, strong) SMValueAndUnit *quantity;

/// Representing http://smartplatforms.org/terms#startDate
@property (nonatomic, copy) NSString *startDate;


@end
